version: "2"
services:
  web:
    build: ./amicsartromanic/app
    ports:
      - "8080:8080"
      - "3005:3005"
    volumes:
      - /home/alemasar/Projects/amicsartromanic/amicsartromanic/app:/app:rw
    environment:
      - NODE_ENV=development
    networks:
      - frontend
networks:
  frontend:
    # Use a custom driver
    driver: bridge