version: "2"
services:
  web:
    build: ./amicsartromanic/app
    ports:
      - "8080:8080"
      - "3005:3005"
    volumes:
      - /home/alemasar/Projects/amicsartromanic/amicsartromanic/app:/app:rw
    environment:
      - NODE_ENV=development
    networks:
      - frontend
    entrypoint: "npm run launch"
  admin:
    build: ./amicsartromanic/admin
    ports:
      - "3000:3000"
    volumes:
      - /home/alemasar/Projects/amicsartromanic/amicsartromanic/admin:/admin:rw
    environment:
      - NODE_ENV=development
    networks:
      - admin
    entrypoint: "npm run launch"
networks:
  frontend:
    # Use a custom driver
    driver: bridge
  admin:
    # Use a custom driver
    driver: bridge