version: '2'
services:
  swaggerui:
    build: .
    ports:
      - 80:80
    hostname: swaggerui
    volumes:
      - ./swagger.json:/app/swagger/swagger.json


  # swaggerui_novolume:
  #   build: .
  #   ports:
  #     - 8080:80
  #   hostname: swaggerui