  
FROM python:3.6

#EXPOSE 5000

#WORKDIR /usr/src/app

#COPY requirements.txt /usr/src/app
#COPY . /usr/src/app
#RUN pip install -r requirements.txt
#COPY .flaskenv /usr/src/app
#COPY /app /usr/src/app

#RUN ls -la

#ENV FLASK_APP=backend-api.py

#COPY backend-api.py /usr/src/app
#CMD flask run
WORKDIR /usr/src/backend-api
COPY . /usr/src/backend-api
RUN pip install -r requirements.txt
EXPOSE 5000
ENV FLASK_APP=backend-api.py
CMD flask run