swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /add:
    post:
      operationId: "app.components.hello_world"
      consumes:
        - "application/json"
      tags:
        - "hello_world"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      parameters:
        - name: component
          in: body
          description: Component to create
          schema:
            $ref: '#/definitions/Component'

      responses:
        200:
          description: OK
  /addNew:
    post:
      operationId: "app.news.addNew"
      consumes:
        - "application/json"
      tags:
        - "New"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      parameters:
        - name: new
          in: body
          description: Component to create
          schema:
            $ref: '#/definitions/News'

      responses:
        200:
          description: OK

  /addImage:
    post:
      operationId: "app.news.addImage"
      consumes:
        - "multipart/form-data"
      tags:
        - "Image"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      parameters:
        - name: image
          in: formData
          description: Component to create
#          required: false
          type: file
#        - name: news_image
#          in: body
#          description: Additional data to pass to server
#          required: false
#          type: array
#          items:
#            image:
#              type: string
#            type: object
#            properties:
#              image:
#                type: string
#              footer:
#                type: file

      responses:
        200:
          description: OK

definitions:
  Component:
    type: object
    properties:
      component_name:
        type: string
        description: First name of person to create
      component_tag:
        type: string
        description: First name of person to create
      component_base_path:
        type: string
        description: First name of person to create
      component_scss_path:
        type: string
        description: First name of person to create
      component_js_path:
        type: string
        description: First name of person to create
      component_template_path:
        type: string
        description: First name of person to create
  News:
    type: object
    properties:
      news_summary:
        type: string
        description: Summary of the new to create
      news_body:
        type: string
        description: Body of the new to create
      news_image:
        type: array
        items:
          type: object
          properties:
            images_path:
              type: string
            images_footer:
              type: string
