  admin:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/admin/:rw
    environment:
      - NODE_ENV=dev
    command: >
      sh -c '
        if test -d node_modules; 
        then 
          echo node_modules_exists ; 
        else 
          npm install ;
        fi && 
        npm run build &&
        npm run build-server &&
        npm run server
      '